In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
data = pd.read_excel("iris_train.xlsx")

In [6]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width            class
0           5.0          2.0           3.5          1.0  Iris-versicolor
1           6.3          2.7           4.9          1.8   Iris-virginica
2           5.8          2.7           5.1          1.9   Iris-virginica
3           6.5          2.8           4.6          1.5  Iris-versicolor
4           5.7          2.8           4.5          1.3  Iris-versicolor

In [10]:
x = data.iloc[: , :-1]

In [12]:
y= data.iloc[:, -1]

In [13]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.0          2.0           3.5          1.0
1             6.3          2.7           4.9          1.8
2             5.8          2.7           5.1          1.9
3             6.5          2.8           4.6          1.5
4             5.7          2.8           4.5          1.3
..            ...          ...           ...          ...
115           5.4          3.9           1.3          0.4
116           5.8          4.0           1.2          0.2
117           5.2          4.1           1.5          0.1
118           5.5          4.2           1.4          0.2
119           5.7          4.4           1.5          0.4

[120 rows x 4 columns]

In [15]:
y

0      Iris-versicolor
1       Iris-virginica
2       Iris-virginica
3      Iris-versicolor
4      Iris-versicolor
            ...
115        Iris-setosa
116        Iris-setosa
117        Iris-setosa
118        Iris-setosa
119        Iris-setosa
Name: class, Length: 120, dtype: object

In [65]:
model = RandomForestClassifier()
model.fit(x.values,y.values)

RandomForestClassifier()

In [66]:
predictions= model.predict([[6 , 2.2 , 	4 ,1]])

In [21]:
predictions

array(['Iris-versicolor'], dtype=object)

In [54]:
#To test all the data from the Iris_test

In [56]:
datatest = pd.read_excel("iris_test.xlsx")

In [57]:
x_test = datatest.iloc[: , :-1]

In [68]:
predictions = model.predict(x_test.values)

In [69]:
predictions

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica'],
      dtype=object)